// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vendas.Data;

#nullable disable

namespace Vendas.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    partial class AplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Vendas.Models.Cadastro.CidadeModel", b =>
                {
                    b.Property<int>("IDCIDADE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDCIDADE"));

                    b.Property<int>("EstadoIDESTADO")
                        .HasColumnType("int");

                    b.Property<int>("IBGE")
                        .HasColumnType("int");

                    b.Property<int>("IDESTADO")
                        .HasColumnType("int");

                    b.Property<string>("NOME")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Uf")
                        .HasColumnType("int");

                    b.HasKey("IDCIDADE");

                    b.HasIndex("EstadoIDESTADO");

                    b.ToTable("Cidade");
                });

            modelBuilder.Entity("Vendas.Models.Cadastro.ClienteModel", b =>
                {
                    b.Property<int>("Idcliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Idcliente"));

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cfop")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cntrecdesp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Fisicajuridica")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Idcondicopagamento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Idestado")
                        .HasColumnType("int");

                    b.Property<string>("Idformapagamento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Idmunicipio")
                        .HasColumnType("int");

                    b.Property<int>("Idpais")
                        .HasColumnType("int");

                    b.Property<decimal>("Limitecredito")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nomefantasia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Obs")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Refcomercial")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Refpessoal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Regiao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rg")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Setor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Valorminimo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Zona")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Idcliente");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Vendas.Models.Cadastro.EmpresaModel", b =>
                {
                    b.Property<int>("Idempresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Idempresa"));

                    b.Property<string>("Aliquotaicms")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cnae")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Crt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Dataedicao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Datainclusao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Dtcadastro")
                        .HasColumnType("datetime");

                    b.Property<string>("Editadopor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Idestado")
                        .HasColumnType("int");

                    b.Property<int>("Idmunicipio")
                        .HasColumnType("int");

                    b.Property<int>("Idpais")
                        .HasColumnType("int");

                    b.Property<string>("Incluidopor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Inscestadual")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Inscmunicipal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nomefantasia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Situacaofiscal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titular")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Idempresa");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("Vendas.Models.Cadastro.EstadoModel", b =>
                {
                    b.Property<int>("IDESTADO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDESTADO"));

                    b.Property<string>("DDD")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IBGE")
                        .HasColumnType("int");

                    b.Property<int>("IDPAIS")
                        .HasColumnType("int");

                    b.Property<string>("NOME")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IDESTADO");

                    b.ToTable("Estado");
                });

            modelBuilder.Entity("Vendas.Models.Cadastro.PaisModel", b =>
                {
                    b.Property<int>("IDPAIS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDPAIS"));

                    b.Property<int>("BACEN")
                        .HasColumnType("int");

                    b.Property<string>("NOME")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NOME_PT")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SIGLA")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IDPAIS");

                    b.ToTable("Pais");
                });

            modelBuilder.Entity("Vendas.Models.Cadastro.CidadeModel", b =>
                {
                    b.HasOne("Vendas.Models.Cadastro.EstadoModel", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoIDESTADO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");
                });
#pragma warning restore 612, 618
        }
    }
}
